import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { launchChromium } from '../browser.mjs';
const DIR = new URL('./lust/', import.meta.url).pathname; rmSync(DIR, { recursive: true, force: true }); mkdirSync(DIR, { recursive: true });
const b = await launchChromium();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(String(e).slice(0, 200)));
await p.goto('http://127.0.0.1:4421/?city=1&x=6.3&z=49', { waitUntil: 'networkidle' }); await p.waitForTimeout(6000);
const stick = (x, y) => p.evaluate(([x, y]) => { for (const el of document.querySelectorAll('div')) if (el.__stick) { el.__stick(x, y); return true; } return false; }, [x, y]);
const btns = async () => (await p.evaluate(() => [...document.querySelectorAll('[role=button],button')].map((e) => (e.innerText.trim() || e.getAttribute('aria-label') || '').replace(/\n/g, ' ')).filter(Boolean))).join(' | ');
await stick(0, -0.3); await p.waitForTimeout(400); await stick(0, 0); await p.waitForTimeout(4500);
const cdp = await ctx.newCDPSession(p); const frames = []; const marks = [];
cdp.on('Page.screencastFrame', async (f) => { frames.push({ t: f.metadata.timestamp, d: f.data }); await cdp.send('Page.screencastFrameAck', { sessionId: f.sessionId }).catch(() => {}); });
const mark = (l) => { marks.push({ label: l, t: Date.now() / 1000 }); console.log('mark', l); };
await cdp.send('Page.startScreencast', { format: 'jpeg', quality: 88, maxWidth: 780, maxHeight: 1688, everyNthFrame: 1 });
mark('street'); await p.waitForTimeout(800);
await stick(0, -0.7);
for (let i = 0; i < 40; i++) { await p.waitForTimeout(300); if (await p.getByRole('button', { name: /היכנס/ }).count()) break; }
await p.waitForTimeout(500); await stick(0, 0); mark('window'); await p.waitForTimeout(2800);
await p.getByRole('button', { name: /היכנס/ }).first().click(); mark('enter'); await p.waitForTimeout(3500);
mark('look'); await stick(0.55, 0); await p.waitForTimeout(900); await stick(0, 0); await p.waitForTimeout(700); await stick(-0.55, 0); await p.waitForTimeout(1500); await stick(0, 0); await p.waitForTimeout(1200);
await p.getByRole('button', { name: /מה אפשר להזמין כאן/ }).first().click(); mark('products'); await p.waitForTimeout(3500);
console.log('PRODUCTS', await btns());
await p.getByRole('button', { name: 'LUST FOR HER' }).first().click({ force: true }); mark('product'); await p.waitForTimeout(3500);
console.log('AFTER', await btns()); await p.screenshot({ path: 'lr_product.png' });
await cdp.send('Page.stopScreencast');
const t0 = frames[0].t;
const idx = frames.map((f, i) => { const n = String(i).padStart(5, '0') + '.jpg'; writeFileSync(DIR + n, Buffer.from(f.d, 'base64')); return { t: +(f.t - t0).toFixed(3), f: n }; });
writeFileSync(DIR + 'index.json', JSON.stringify({ frames: idx, marks: marks.map((m) => ({ label: m.label, t: +(m.t - t0).toFixed(3) })) }));
console.log('frames', frames.length, idx.at(-1).t, 'errors', errs.join(' | '));
await b.close();
