import type { WorldAssetSources } from "@pro-now/ui";

/**
 * THE ART THAT HAS ACTUALLY ARRIVED.
 *
 * One line per delivered asset, and nothing else. An id that is not in here
 * renders as `AssetSlot`'s grey rectangle, which is the correct and
 * deliberately ugly picture of "commissioned, not delivered".
 *
 * Generated by `tools/design-preview/ingest-pack.mjs` from the contents of
 * `public/world/`. Regenerate rather than edit by hand: a list that is
 * maintained separately from the folder is a list that drifts from it.
 */
export const worldSources: WorldAssetSources = {
  avatar_01_portrait: { uri: "./world/avatar_01_portrait.webp" },
  avatar_02_portrait: { uri: "./world/avatar_02_portrait.webp" },
  avatar_03_portrait: { uri: "./world/avatar_03_portrait.webp" },
  avatar_04_portrait: { uri: "./world/avatar_04_portrait.webp" },
  avatar_05_portrait: { uri: "./world/avatar_05_portrait.webp" },
  avatar_06_portrait: { uri: "./world/avatar_06_portrait.webp" },
  avatar_07_portrait: { uri: "./world/avatar_07_portrait.webp" },
  avatar_08_portrait: { uri: "./world/avatar_08_portrait.webp" },
  avatar_09_portrait: { uri: "./world/avatar_09_portrait.webp" },
  avatar_10_portrait: { uri: "./world/avatar_10_portrait.webp" },
  avatar_11_portrait: { uri: "./world/avatar_11_portrait.webp" },
  avatar_12_portrait: { uri: "./world/avatar_12_portrait.webp" },
  character_appliance_icon: { uri: "./world/character_appliance_icon.webp" },
  character_appliance_world: { uri: "./world/character_appliance_world.webp" },
  character_auto_icon: { uri: "./world/character_auto_icon.webp" },
  character_auto_world: { uri: "./world/character_auto_world.webp" },
  character_build_icon: { uri: "./world/character_build_icon.webp" },
  character_build_world: { uri: "./world/character_build_world.webp" },
  character_care_icon: { uri: "./world/character_care_icon.webp" },
  character_care_world: { uri: "./world/character_care_world.webp" },
  character_hair_icon: { uri: "./world/character_hair_icon.webp" },
  character_hair_world: { uri: "./world/character_hair_world.webp" },
  character_help_icon: { uri: "./world/character_help_icon.webp" },
  character_help_world: { uri: "./world/character_help_world.webp" },
  character_home_icon: { uri: "./world/character_home_icon.webp" },
  character_home_world: { uri: "./world/character_home_world.webp" },
  character_move_icon: { uri: "./world/character_move_icon.webp" },
  character_move_world: { uri: "./world/character_move_world.webp" },
  character_pets_icon: { uri: "./world/character_pets_icon.webp" },
  character_pets_world: { uri: "./world/character_pets_world.webp" },
  character_tech_icon: { uri: "./world/character_tech_icon.webp" },
  character_tech_world: { uri: "./world/character_tech_world.webp" },
  character_well_icon: { uri: "./world/character_well_icon.webp" },
  character_well_world: { uri: "./world/character_well_world.webp" },
  courier_scooter: { uri: "./world/courier_scooter.webp" },
  district_appliance: { uri: "./world/district_appliance.webp" },
  district_auto: { uri: "./world/district_auto.webp" },
  district_care: { uri: "./world/district_care.webp" },
  district_hair: { uri: "./world/district_hair.webp" },
  district_home: { uri: "./world/district_home.webp" },
  district_move: { uri: "./world/district_move.webp" },
  district_nails: { uri: "./world/district_nails.webp" },
  district_pets: { uri: "./world/district_pets.webp" },
  district_tech: { uri: "./world/district_tech.webp" },
  district_well: { uri: "./world/district_well.webp" },
  dog_walker: { uri: "./world/dog_walker.webp" },
  /*
   * INSIDE THE SHOP, ONE FILE PER TRADE.
   *
   * Amit, four times: *"אני חייב להיכנס לתוך החנות ממש."* These are the
   * interiors, cut from the open-front shops in the generated pack —
   * the part behind the shutter, which is the picture "going inside"
   * needs and the one a façade cannot give however far you zoom.
   *
   * Named by `venueInteriorAssetId`, so the renderer finds them without
   * knowing where they came from. The trades still missing one fall
   * back to the drawn room, which says on its face that it is a
   * drawing.
   */
  hair_barbershop_hero: { uri: "./world/hair_barbershop_hero.webp" },
  auto_garage_hero: { uri: "./world/auto_garage_hero.webp" },
  pets_salon_hero: { uri: "./world/pets_salon_hero.webp" },
  appliance_workshop_hero: { uri: "./world/appliance_workshop_hero.webp" },
  care_studio_hero: { uri: "./world/care_studio_hero.webp" },
  home_workshop_hero: { uri: "./world/home_workshop_hero.webp" },
  moving_van: { uri: "./world/moving_van.webp" },
  shared_ground_street: { uri: "./world/shared_ground_street.webp" },
  tow_truck: { uri: "./world/tow_truck.webp" },
  welcome_hero: { uri: "./world/welcome_hero.webp" },
  world_ground_grass: { uri: "./world/world_ground_grass.webp" },
  world_ground_mat_1: { uri: "./world/world_ground_mat_1.webp" },
  world_ground_mat_2: { uri: "./world/world_ground_mat_2.webp" },
  world_ground_mat_3: { uri: "./world/world_ground_mat_3.webp" },
  world_ground_mat_4: { uri: "./world/world_ground_mat_4.webp" },
  world_neighbourhood: { uri: "./world/world_neighbourhood.webp" },
};
