import { launchChromium } from '../browser.mjs';
const b = await launchChromium();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
const p = await ctx.newPage();
const press = async (re) => { const loc = p.locator('[role=button],button').filter({ visible: true }); const c = await loc.count(); for (let i = 0; i < c; i++) { const el = loc.nth(i); const a = ((await el.getAttribute('aria-label')) || '').trim(); const t = ((await el.innerText().catch(() => '')) || '').trim().replace(/\s+/g, ' '); const lab = re.test(a) ? a : t; if (re.test(lab)) { await el.click({ force: true }); await p.waitForTimeout(1500); return lab; } } return null; };
const txt = async () => (await p.evaluate(() => document.body.innerText)).replace(/\s+/g, ' ');
await p.goto('http://127.0.0.1:4421/?time=day'); await p.locator('text=אני צריך מקצוען').first().waitFor();
await press(/^אני צריך מקצוען/); await p.getByLabel('מספר טלפון').fill('0501234567'); await press(/^שליחת קוד/); await p.getByLabel('קוד האימות').fill('123456'); await press(/^כניסה/);
await press(/^דילוג על ההסבר/); await press(/^דמות 1$/); await press(/^(אישור הדמות|זו אני)/);
const before = await txt();
await press(/^הקלטה$/); await p.waitForTimeout(2000);
const after = await txt();
const diff = after.split(' ').filter((w) => !before.includes(w)).join(' ');
console.log('home record → new text:', diff.slice(0, 200) || '(nothing)');
await p.screenshot({ path: 'out/deny_home.png' });
await press(/^תפריט$/); const m1 = /העבודות שלי/.test(await txt());
await press(/^תפריט$/); const m2 = /העבודות שלי/.test(await txt());
console.log('menu open after 1st:', m1, 'after 2nd:', m2);
await p.screenshot({ path: 'out/deny_menu.png' });
await b.close();
