/**
 * WHAT THE WORLD IS WAITING FOR, AS A BRIEF SOMEBODY CAN DRAW FROM.
 *
 * ---------------------------------------------------------------------
 * WHY THIS IS GENERATED AND NOT WRITTEN
 * ---------------------------------------------------------------------
 * `art-delivery.test.ts` already reports which asset ids the world asks
 * for and has not received — twenty of them — and it deliberately does
 * not fail over it, because most of them legitimately have not arrived
 * and a red test nobody can fix is a red test everybody learns to skip.
 *
 * What it prints is a list of ids. An id is not a brief. `district_help`
 * says nothing about what to draw, how big, from what angle, or why the
 * scene needs it, and the answers to all four are already in this
 * repository — in `AVATAR_CHOICES`, in the asset manifest, and in
 * `/docs/03c-LIVING-MAP-ART-DIRECTION.md`. They are just in three places
 * and none of them is a page somebody can work from.
 *
 * So this assembles one, from those three sources. A brief written by
 * hand would start drifting the moment an asset lands; this cannot,
 * because it is derived from the same declarations the renderer reads.
 *
 * ---------------------------------------------------------------------
 * WHY IT MATTERS MORE THAN IT LOOKS
 * ---------------------------------------------------------------------
 * The living map draws nothing at all for an asset it does not have —
 * "an invisible courier is better than a grey rectangle sliding down the
 * road pretending to be one". That rule is right and it has a cost: the
 * street is quiet because twenty files are missing, not because the
 * engine is thin. Every one of these is a thing that would be moving.
 *
 * Run: `npm run art:brief`
 */
import { readdirSync } from "node:fs";
import { join } from "node:path";

const ASSET_DIR = "apps/customer-mobile/assets/world";

const delivered = new Set(
  readdirSync(ASSET_DIR)
    .filter((f) => f.endsWith(".webp"))
    .map((f) => f.replace(/\.webp$/, ""))
);

/**
 * The shared rules, from `/docs/03c-LIVING-MAP-ART-DIRECTION.md`. Repeated
 * here rather than linked because a brief that requires opening another
 * document is a brief half of which gets skipped.
 */
const HOUSE_STYLE = [
  "3/4 miniature perspective, camera 45–55° above. Façades AND roofs visible.",
  "NOT mathematical isometric — a true isometric grid reads as SimCity, which is the opposite of the target.",
  "Transparent background (PNG in, WebP out). No baked ground, no baked shadow: the engine draws the contact shadow.",
  "Night palette, warm artificial light. The world is lit; it is not a daylight illustration dimmed.",
  "One canonical character design per person across every file they appear in — same clothing, same hair, same equipment.",
];

/**
 * Twelve customer avatars. The PORTRAITS exist; every one of the BACKS is
 * missing, which is why the customer's own figure cannot walk away from
 * the camera down their own street.
 */
const AVATARS = [
  { n: "01", presentation: "WOMAN", note: "" },
  { n: "02", presentation: "WOMAN", note: "" },
  { n: "03", presentation: "WOMAN", note: "כיסוי ראש" },
  { n: "04", presentation: "WOMAN", note: "" },
  { n: "05", presentation: "WOMAN", note: "" },
  { n: "06", presentation: "MAN", note: "" },
  { n: "07", presentation: "MAN", note: "" },
  { n: "08", presentation: "MAN", note: "כיפה" },
  { n: "09", presentation: "MAN", note: "" },
  { n: "10", presentation: "NEUTRAL", note: "" },
  { n: "11", presentation: "NEUTRAL", note: "" },
  { n: "12", presentation: "NEUTRAL", note: "" },
];

const RIDES = [
  { id: "ride_scooter", he: "קטנוע PRO NOW", ratio: "255 × 197 · anchor y = 1 (wheels on the ground)" },
  { id: "ride_van", he: "ואן PRO NOW", ratio: "418 × 195 · anchor y = 1" },
  { id: "ride_kick", he: "קורקינט PRO NOW", ratio: "roughly 150 × 190 · anchor y = 1" },
];

const DISTRICTS = [
  { id: "district_build", he: "שכונת הבנייה והשיפוצים", note: "פיגום, ערימת חול, מכולה — לא אתר בנייה פעיל ורועש" },
  { id: "district_help", he: "שכונת העזרה הכללית", note: "חזית שקטה: הנדימן, זוג ידיים, שליחויות קטנות" },
];

const lines = [];
const out = (s = "") => lines.push(s);

out("# ART BRIEF — what the living map is waiting for");
out("");
out("Generated by `npm run art:brief`. Do not edit by hand: it is derived");
out("from AVATAR_CHOICES, the asset manifest and the art direction, so it");
out("cannot disagree with what the renderer actually asks for.");
out("");
out("## House style — every file below");
out("");
for (const rule of HOUSE_STYLE) out(`- ${rule}`);
out("");

let missingCount = 0;
const section = (title, why) => {
  out("");
  out(`## ${title}`);
  out("");
  out(why);
  out("");
};

// ---- avatars -------------------------------------------------------
const missingAvatars = AVATARS.filter((a) => !delivered.has(`avatar_${a.n}_world_back`));
if (missingAvatars.length > 0) {
  section(
    `Customer avatars, from behind (${missingAvatars.length})`,
    [
      "The customer picks a figure and then walks their own street as it. The",
      "portrait is what they choose from; this is what they are, seen from",
      "behind, because a walking figure is nearly always going away from the",
      "camera. Without it there is nobody to be.",
      "",
      "Full body, seen from BEHIND and slightly above, mid-stride. Same person",
      "as the matching `avatar_NN_portrait.webp` — same clothes, same hair.",
      "Roughly 1.7m tall in world scale; the engine sizes them, so what matters",
      "is that the proportions are a person and the feet are at the bottom edge.",
    ].join("\n")
  );
  for (const a of missingAvatars) {
    missingCount += 1;
    out(
      `- \`avatar_${a.n}_world_back.webp\` — ${a.presentation}${a.note ? ` · ${a.note}` : ""}` +
        `  (matches \`avatar_${a.n}_portrait.webp\`)`
    );
  }
}

// ---- rides ---------------------------------------------------------
const missingRides = RIDES.flatMap((r) =>
  ["back", "side"].filter((angle) => !delivered.has(`${r.id}_${angle}`)).map((angle) => ({ ...r, angle }))
);
if (missingRides.length > 0) {
  section(
    `Vehicles, two angles each (${missingRides.length})`,
    [
      "A professional who drives is drawn as their vehicle, and a vehicle needs",
      "two angles for the same reason a person does: `_side` is the one the",
      "customer picks from and sees passing; `_back` is the one that drives away",
      "up the street.",
      "",
      "Both angles must be the SAME vehicle — same colour, same livery, same",
      "PRO NOW mark in the same place. The wheels sit on the bottom edge of the",
      "canvas: the engine puts the shadow under them.",
    ].join("\n")
  );
  for (const r of missingRides) {
    missingCount += 1;
    const what =
      r.angle === "back"
        ? "driving away from the camera, rear three-quarter"
        : "side-on three-quarter, moving right to left";
    out(`- \`${r.id}_${r.angle}.webp\` — ${r.he} · ${what} · ${r.ratio}`);
  }
}

// ---- districts -----------------------------------------------------
const missingDistricts = DISTRICTS.filter((d) => !delivered.has(d.id));
if (missingDistricts.length > 0) {
  section(
    `Neighbourhoods (${missingDistricts.length})`,
    [
      "Each department has a street of its own, and two have no art, so those",
      "trades have nowhere to be shown standing. Same framing as the delivered",
      "`district_*.webp` files — a shopfront row, not a single building.",
    ].join("\n")
  );
  for (const d of missingDistricts) {
    missingCount += 1;
    out(`- \`${d.id}.webp\` — ${d.he} · ${d.note}`);
  }
}

// ---- what the street has no vocabulary for -------------------------
out("");
out("## Not missing files — missing kinds of life");
out("");
out(
  [
    "These have no asset id yet because nothing has been written to draw them,",
    "and they are the reason the street reads as quiet even when every file",
    "above has landed. `WorldLife` knows four things that move: a courier, a",
    "van, a tow truck and one dog walker. Three of its four are vehicles.",
    "",
    "What a street that size actually has, and this one does not:",
    "",
    "- people who are simply THERE — at a café table, on a bench, waiting at a",
    "  crossing. `/docs/03c §16.3` allows this and is the reason it is worth",
    "  saying carefully: *motion without agency is ambience, motion with agency",
    "  is an entity*. Somebody sitting is ambience. Somebody walking purposefully",
    "  toward a door is a claim about an arrival, and needs a source of truth.",
    "- an ordinary pedestrian who is not a professional and not the customer.",
    "- the three ambient moments the code already names and has no art for:",
    "  `amb_window_light`, `amb_birds`, `amb_cat`.",
    "",
    "A figure for each of those, in two or three variations, would do more for",
    "how alive the street feels than any change to the engine.",
  ].join("\n")
);

out("");
out("---");
out("");
out(`**${missingCount} files named above.** ${delivered.size} delivered.`);
out("");

console.log(lines.join("\n"));
